### ISSUE TITLE
realtime staging of exposures with extra files

### ISSUE THREAD

**Issue by sbailey** [desihub/desitransfer#25]
sky*.fits.fz files are currently not included in the checksum-EXPID.sha256sum files, e.g. 20201219/00068903 .  This is causing the realtime data transfer to log an ERROR:
```
ERROR:daemon.py:572:verify_checksum:2020-12-20T04:58:07: /global/cfs/cdirs/desi/spectro/staging/raw/20201219/00068903/checksum-00068903.sha256sum does not match the number of files!
ERROR:daemon.py:364:exposure:2020-12-20T04:58:07: Checksum problem detected for 20201219/00068903!
```
and apparently withhold the exposure in the desi/spectro/staging/raw/NIGHT/EXPID area instead of moving it into desi/spectro/data/NIGHT/EXPID.  It appears that the morning cleanup pass is catching these and moving them into their final location sometime after 6am Pacific Time.

This delay is problematic because it means that these exposures are not processed in realtime by Nightwatch at NERSC (used by the Data Quality Observer who many not have VPN access to the KPNO copy of Nightwatch), and prevents the full pipeline from processing them throughout the night (which could also break the logic for "jointly fit standard stars across multiple exposures of the same tile").

**Suggestion**: if there is an *extra* file that isn't in the checksum file, go ahead of post the exposure just like is happening with the morning cleanup pass.  Only withhold the exposure in the staging area if there is a *missing* file, or a file with a different checksum indicating corruption.

@daqiii (Klaus) comments
> this is likely related to the stop problem that causes one additional sky camera image when the spectrographs are done. if this is a correct assumption it will not get fixed tomorrow as this problem requires more significant work

**Comment by daqiii** [comment]
Fixed now on the ICS side

**Comment by sbailey** [comment]
Thanks @daqiii.  Having the fix on the ICS side removes the urgency of doing anything on the desitransfer side so we can evaluate this after the holidays.

I suggest that we add this robustness feature to desitransfer anyway (go ahead and stage exposures with extra files, but not with missing or corrupted files), but that is no longer urgent if sky files are included in the checksums now.

**Comment by weaverba137** [comment]
The existing procedure is a hold-over from the days when we were planning for the transfer system to *initiate* pipeline processing.  I don't think there's any issue to changing this procedure.

**Comment by sbailey** [comment]
Quoting Ben:
> The existing procedure is a hold-over from the days when we were planning for the transfer system to initiate pipeline processing. I don't think there's any issue to changing this procedure.

Good.  Quoting myself so that I can disagree with myself (i.e. update my opinion...):
> I suggest that we add this robustness feature to desitransfer anyway (go ahead and stage exposures with extra files, but not with missing or corrupted files), but that is no longer urgent if sky files are included in the checksums now.

Even though sky files are now included in the checksums, we continue to have occasional problems with sky and guide files being updated after the checksums are made, resulting in checksum errors.  The consequence of withholding those is that nightwatch doesn't get to see the exposure in realtime, which is problematic for remote data quality assessment.  So I update my suggestion to go ahead and post every exposure received regardless of checksum failures and leave it to Nightwatch and the spectro pipeline to use it at their own risk.  Additionally, let's have checksum failures generate alert emails or equivalent to make sure that humans realize that something is wrong with specific exposures that needs manual attention.

**Comment by weaverba137** [comment]
OK, @sbailey, to be clear, you want *all* exposures transferred to `$DESI_SPECTRO_DATA`, no matter what happens at the checksum stage, correct?

Does that also apply to failures at the initial transfer (rsync) stage?  In other words you  want nothing ever left behind in spectro/staging/raw, with the understanding that pipeline/nightwatch have no quality assurance on the data in `$DESI_SPECTRO_REDUX`? Unless pipeline/nightwatch wants to parse the JSON status file in spectro/staging/status?

I'm already working on the notification emails.
