### ISSUE TITLE
raw data directory-level permissions

### ISSUE THREAD

**Issue by sbailey** [desihub/desitransfer#28]
Currently the raw data *files* have write permissions removed even from the desi-user owner to prevent accidental updates (good).  However the *directories* themselves still have user write permission, meaning that the desi user could accidentally delete files or add files to raw data directories that are supposed to be frozen.  I suggest that we remove write permission from all past directories, and update desitransfer to remove write permission from each new night just before it backs it up to HPSS.  That way we have to be very purposeful about any future updates and are more safe from accidental deletions.

**Comment by weaverba137** [comment]
Purely for the record: I think I tried this in the past and for a reason I can't recall it was more trouble than it was worth.  If nothing else it is worth testing and documenting why it is a pain, even if we don't end up implementing it.

**Comment by weaverba137** [comment]
Closed by #41.
