### ISSUE TITLE
Transfer 'NightSummary' in night logs from KPNO to NERSC

### ISSUE THREAD

**Issue by parfa30** [desihub/desitransfer#34]
With the rsynch of nightlogs/, also transfer all files that include the string 'NightSummary' from KPNO to NERSC. They do not have a '_kpno' tag, but they are only written at KPNO.

**Comment by weaverba137** [comment]
I was able to test this last night (20210421) with a quick hack.  The NightSummary file successfully arrived at NERSC.  I'll create a PR to make the update permanent.
