### ISSUE TITLE
Transfer 'NightSummary' in night logs from KPNO to NERSC

### ISSUE THREAD

**Issue by parfa30** [desihub/desitransfer#36]
This was done before but for some reason it didn't stick. The NIghtSummary files aren't being transferred to NERSC from KPNO.

**Comment by weaverba137** [comment]
It would be a *significant* help in debugging this if you could let me know which nights are affected by this.

**Comment by parfa30** [comment]
This file hasn't been transferred since 20210423 to today. The last I see transferred was on 20210422.

**Comment by weaverba137** [comment]
On or about 20210423, the name of the NightSummary file changed, and I was not informed of this change.  It used to be, *e.g.* NightSummary20210422, but now it appears to be NightSummary20210423.html.

**Comment by weaverba137** [comment]
PS, on 20210422, which is the correct file?  `NightSummary20210422` or `NightSummary20210422.html`?

**Comment by parfa30** [comment]
Ah! That does explain the change. NightSummary*.html is the best file for all nights starting 20210422

**Comment by weaverba137** [comment]
OK, I've copied all NightSummary*.html files to NERSC starting 20210422 up to last night.  I'll update the list of files momentarily.
