### ISSUE TITLE
Trigger pipeline on only a desi file.

### ISSUE THREAD

**Issue by weaverba137** [desihub/desitransfer#4]
Currently the pipeline is activated when three files are present.  Change this so that only a `desi-{exposure}.fits.fz` file needs to be present.  This requires only changing a configuration file, not any actual code.

**Comment by daqiii** [comment]
Ben,
I probably misinterpret this message but we will have exposures that should get transferred that do not have a desi-…exposure fits file. Will DTS still trigger on those (I’m thinking of FVC or Guider studies)
Klaus

**Comment by weaverba137** [comment]
This only has to do with whether the DESI pipeline gets triggered at NERSC *after* an exposure is transferred.  We still transfer every exposure that gets linked into the transfer directory.

**Comment by daqiii** [comment]
Thank you – sorry for the noise
Klaus
