### ISSUE TITLE
Updated NightLog Structure

### ISSUE THREAD

**Issue by parfa30** [desihub/desitransfer#42]
We have streamlined the NightLog and it's output files.

The following changes need to be made to `desi_nightlog_transfer_kpno.txt` and `desi_nightlog_transfer_nersc.txt`:

**Remove** the following folders:
DataQualityAssessment
OperationsScientist
OtherInput

**Add** following folder:
Observers

**Comment by weaverba137** [comment]
Is this change effective immediately?  Are there nights in the past that have not synced correctly due to this change?

**Comment by parfa30** [comment]
This should be effective immediately starting with last night September 12, 2021
