### ISSUE TITLE
Review mirroring of engineering/focalplane

### ISSUE THREAD

**Issue by weaverba137** [desihub/desitransfer#55]
Currently we maintain a mirror copy of `/global/cfs/cdirs/desi/engineering/focalplane` in Tucson, which is meant to be updated daily.  However, the amount of data -- and especially the number of files (inodes) -- in that directory has grown so large that the transfer of the directory slows down or prevents the mirroring of more critical data such as raw data or daily reductions.

The majority of the inodes are in `/global/cfs/cdirs/desi/engineering/focalplane/archive`.

Are there *subdirectories* in `engineering/focalplane` that you would consider irreplaceable enough that they should continue to be mirrored to an off-site location?

Also note that we *do not* currently maintain active tape backups of any data in `engineering/focalplane`.

**Comment by daqiii** [comment]
I would also like to remove the bulk of these files from the DESI cluster at KPNO. Right now it's 169 GB. Not all that much but the log files are dating back to 2019. I will ask Ann to remove everything before 2023/1/1 next Monday. Please speak up if you see a problem with that.

**Comment by weaverba137** [comment]
@daqiii, let's make sure we are able to copy engineering data to NERSC before you delete anything.  We have not copied any engineering data at all during the network outage.

**Comment by weaverba137** [comment]
For reference, the focalplane directories that are normally synced to NERSC are:

* `/data/focalplane/calibration` --> `desi/engineering/focalplane/calibration`
* `/data/focalplane/logs/calib_logs` --> `desi/engineering/focalplane/logs/calib_logs`
* `/data/focalplane/logs/kpno` --> `desi/engineering/focalplane/logs/kpno`
* `/data/focalplane/logs/sequence_logs` --> `desi/engineering/focalplane/logs/sequence_logs`
* `/data/focalplane/fp_temp_files` --> `desi/engineering/focalplane/hwtables` (CSV files only)

**Comment by daqiii** [comment]
Sure – but the network outage was in 2023 so the old data has been copied
Klaus

From: Benjamin Alan Weaver ***@***.***>
Date: Wednesday, September 20, 2023 at 2:44 PM
To: desihub/desitransfer ***@***.***>
Cc: Honscheid, Klaus ***@***.***>, Mention ***@***.***>
Subject: Re: [desihub/desitransfer] Review mirroring of engineering/focalplane (Issue #55)
@daqiii, let's make sure we are able to copy engineering data to NERSC before you delete anything. We have not copied any engineering data at all during the network outage. — Reply to this email directly, view it on GitHub, or unsubscribe. You


@daqiii<https://urldefense.com/v3/__https:/github.com/daqiii__;!!KGKeukY!3DmTo_vEYeAvTyZ2AGvoUj_TIEoIP9XLZ3qLTsYlmluISRQJoGw5-YQj15oPwNIDLXZ0troI_lGsMb7CU51mSnab9A$>, let's make sure we are able to copy engineering data to NERSC before you delete anything. We have not copied any engineering data at all during the network outage.

**Comment by weaverba137** [comment]
I know, and hopefully everything will be synced by Monday, but it pays to be careful about these things.

**Comment by daqiii** [comment]
We can wait a few more days – I think the main thing now is to hear back from the FP group how much of this data they actually need (to keep)


From: Benjamin Alan Weaver ***@***.***>
Date: Wednesday, September 20, 2023 at 3:03 PM
To: desihub/desitransfer ***@***.***>
Cc: Honscheid, Klaus ***@***.***>, Mention ***@***.***>
Subject: Re: [desihub/desitransfer] Review mirroring of engineering/focalplane (Issue #55)
I know, and hopefully everything will be synced by Monday, but it pays to be careful about these things. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: 


I know, and hopefully everything will be synced by Monday, but it pays to be careful about these things.

**Comment by weaverba137** [comment]
At the instrument operations meeting today, we concluded:

1. We will leave existing daily engineering data transfers as-is.
2. The `engineering/focalplane/archive` directory does not need to be copied to the NOIRLab mirror. This is easy to implement and is being tested already.
